export const MasterPool = {
    "MstClass": require("./master/MstClass.json"),
    "MstCombineLimit": require("./master/MstCombineLimit.json"),
    "MstCombineSkill": require("./master/MstCombineSkill.json"),
    "MstFriendship": require("./master/MstFriendship.json"),
    "MstItem": require("./master/MstItem.json"),
    "MstSkill": require("./master/MstSkill.json"),
    "MstSkillDetail": require("./master/MstSkillDetail.json"),
    "MstSkillLv": require("./master/MstSkillLv.json"),
    "MstSvt": require("./master/MstSvt.json"),
    "MstSvtCard": require("./master/MstSvtCard.json"),
    "MstSvtComment": require("./master/MstSvtComment.json"),
    "MstSvtExp": require("./master/MstSvtExp.json"),
    "MstSvtLimit": require("./master/MstSvtLimit.json"),
    "MstSvtSkill": require("./master/MstSvtSkill.json"),
    "MstSvtTreasureDevice": require("./master/MstSvtTreasureDevice.json"),
    "MstTreasureDevice": require("./master/MstTreasureDevice.json"),
    "MstTreasureDeviceLv": require("./master/MstTreasureDeviceLv.json"),
};